[build]
  command = "npm install && npm run build"
  functions = "dist/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  directory = "dist/functions"
  
  # Opcional: configuraciones adicionales de funciones
  included_files = [
    "dist/functions/**"
  ]
